### ISSUE TITLE
Versioning of the mod requirements

### ISSUE THREAD

**Issue by andersoyvind** [raiguard/Factorio-BottleneckLite#11]
Hi.

I notice that you like to push the base game requirements to beyond stable. I guess it is due to using new experimental features in the Factorio api, but for us users that keep Factorio at stable, this is a tiny hassle.

I know, updating mods based on a save game will download latest versions, regardless of info.json content, compared to syncing with a server, but regardless, now I have to download old versions or play without the mod.

Due to the lack of support from the Factorio client on this matter, would it be a better practice to keep mods with base set to experimental versions from being deployed, until stable base is released? Or is it a better practice to just play Factorio experimental?

**Comment by raiguard** [comment]
There has been a bug in the mod updater that would download versions that are too new for your Factorio version, but that has been fixed in 1.1.87. The reason I push updates that require experimental versions is because I am utilizing new APIs added in those versions. If a mod is compatible with stable, I will set its dependency to match.

Are you saying that sync-mods-with-save is downloading versions that are too new for you to run? If so, then that's a bug in the game that I can look into.

**Comment by andersoyvind** [comment]
Thanks! Isn't the timing perfect? I've been playing a game for one month at 1.1.85, then started a new one yesterday, of which I decided to go back to stable (1.1.80). I cannot sync mods against newer saves, so I pick an old one (1.1.76), that used BottleneckLite 1.2.4. sync-mods-with-save.

Here the Factorio client downloads 1.2.7 as that is the latest one, with a base req > current version. So yes, that is my saying.

But it must have been less than an hour before I posted the issue, that Factorio is updated to 1.1.87! The odds!
